name = "vehicle-finder"
main = "src/worker.ts"
compatibility_date = "2026-08-25"

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[triggers]
crons = ["0 */12 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "vehicle-finder"
database_id = "local-vehicle-finder"
migrations_dir = "migrations"
