INSERT INTO users (id, email, display_name, locale, created_at)
VALUES (
  'family',
  NULL,
  'Family',
  'en-US',
  '2026-08-25T00:00:00.000Z'
)
ON CONFLICT(id) DO UPDATE SET
  email = excluded.email,
  display_name = excluded.display_name,
  locale = excluded.locale;

INSERT INTO saved_searches (
  id,
  user_id,
  name,
  enabled,
  config_json,
  created_at,
  updated_at
)
VALUES (
  'family-replacement-vehicle',
  'family',
  'Family replacement vehicle',
  1,
  '{"schemaVersion":1,"id":"family-replacement-vehicle","userId":"family","name":"Family replacement vehicle","enabled":true,"geography":{"center":{"label":"Happy Ln, Cypress, TX","latitude":29.9691,"longitude":-95.6972},"radiusMiles":25},"budgets":{"cashTarget":10000,"stretchTarget":15000,"absoluteMax":17000},"filters":{"makes":["Honda","Toyota","Ford"],"models":["Odyssey","Pilot","Sienna","Highlander","CR-V","Edge","Explorer"],"excludedExteriorColors":["black"],"minSeats":5,"titleStatuses":["clean"],"sellerTypes":["dealer","private"],"excludeNonRunning":true,"excludeUnresolvedMajorSafetyIssues":true},"preferences":{"vehicleTypeWeights":{"minivan":1,"three-row-suv":0.9,"two-row-suv":0.7,"sedan":0},"modelPreferences":[{"make":"Honda","model":"Odyssey","level":"primary","weight":1},{"make":"Honda","model":"Pilot","level":"primary","weight":1},{"make":"Toyota","model":"Sienna","level":"primary","weight":0.95},{"make":"Toyota","model":"Highlander","level":"primary","weight":0.95},{"make":"Honda","model":"CR-V","level":"secondary","weight":0.7},{"make":"Ford","model":"Explorer","level":"secondary","weight":0.6},{"make":"Ford","model":"Edge","level":"secondary","weight":0.5}],"mileageTargets":{"cashIdealMax":120000,"cashSoftMax":140000,"stretchIdealMax":100000,"stretchSoftMax":120000},"colorPreferences":{"preferredExteriorColors":["white","silver","light gray"],"avoidExteriorColors":["black","dark blue","dark gray"],"reason":"reduce cabin heat"}},"scoring":{"vehicleWeights":{"reliabilityModelYearRisk":25,"maintenanceServiceHistory":20,"mileageRelativeToAge":15,"titleAccidentOwnershipHistory":15,"mechanicalPhysicalCondition":10,"familyVehicleRoleFit":10,"trimUsefulFeatures":5},"dealWeights":{"priceVsComparableListings":30,"effectivePurchaseCost":20,"vehicleScoreContribution":20,"priceVsSavedSearchBudget":10,"listingAgePriceMovement":8,"sellerConfidence":5,"distance":4,"listingCompletenessTransparency":3},"riskTolerance":"low"},"notifications":{"minimumVehicleScore":70,"minimumDealScore":75,"notifyOnNewListing":true,"notifyOnPriceDrop":true,"minimumPriceDrop":500},"workflow":{"purchaseDeadline":"2026-09-14","willingToTravelBeyondRadius":true,"privatePartyAllowed":true,"financingPreference":"acceptable","preferredInspectionProviderId":"corbs-auto-grand-rd-cypress-tx","immediateMaintenanceBudget":800}}',
  '2026-08-25T00:00:00.000Z',
  '2026-08-25T00:00:00.000Z'
)
ON CONFLICT(id) DO UPDATE SET
  user_id = excluded.user_id,
  name = excluded.name,
  enabled = excluded.enabled,
  config_json = excluded.config_json,
  updated_at = excluded.updated_at;

INSERT INTO sellers (
  id,
  type,
  name,
  phone,
  website_url,
  latitude,
  longitude,
  location_label,
  created_at,
  updated_at
)
VALUES
  (
    'seller-trade-lane-motors',
    'dealer',
    'Trade Lane Motors',
    NULL,
    'https://www.tradelanemotors.com',
    29.9697,
    -95.697,
    'Cypress, TX',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'seller-king-queen-auto',
    'dealer',
    'Mr. King and Mrs. Queens Auto Finance LLC',
    NULL,
    'https://www.kingqueenauto.com',
    29.9476,
    -95.5843,
    '11830 Jones Road, Houston, TX 77070',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'seller-toyo-financial-group',
    'dealer',
    'Toyo Financial Group',
    NULL,
    'https://www.toyofg.com',
    29.935,
    -95.6469,
    '22226 Northwest Fwy, Cypress, TX 77429',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'seller-vsa-motorcars',
    'dealer',
    'VSA Motorcars',
    NULL,
    'https://www.vsamotorcars.com',
    29.9809,
    -95.655,
    '12212 Cypress N. Houston RD #1, Cypress, TX 77429',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'seller-autostrade',
    'dealer',
    'Autostrade',
    '832-717-6226',
    'https://www.autostradetx.net',
    NULL,
    NULL,
    '23539 State Highway 249, Tomball, TX 77375-8233',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'seller-ride-motors',
    'dealer',
    'Ride Motors LLC',
    '346-698-6226',
    'https://www.ridemotorsllc.com',
    NULL,
    NULL,
    '19005 FM 529 Rd STE 9G, Cypress, TX 77433',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'seller-auto-land-of-texas',
    'dealer',
    'Auto Land of Texas',
    '(832) 869-4969',
    'https://www.autolandoftexas.com',
    29.9471,
    -95.6128,
    '12001 Cypress N Houston Rd, Cypress, TX 77429',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'seller-i90-motors',
    'dealer',
    'I 90 Motors',
    '832-734-8937',
    'https://www.i90motorstx.com',
    29.8795,
    -95.7039,
    '19140 FM 529 Road, Cypress, TX 77433',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'seller-texans-auto-group',
    'dealer',
    'Texans Auto Group',
    '281-288-3388',
    'https://texansautogroup.com',
    30.0703,
    -95.4935,
    '4919 Farm to Market 2920, Spring, TX 77388',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'seller-lone-star-auto-center',
    'dealer',
    'Lone Star Auto Center',
    '281-355-5060',
    'https://www.lonestarautocenter.com',
    30.0771,
    -95.4305,
    '21602 North Fwy, Spring, TX 77373',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'seller-spring-motors',
    'dealer',
    'Spring Motors',
    '281-377-9946',
    'https://www.spring-motors.com',
    30.0669,
    -95.4407,
    '20819 Sunshine Lane, Spring, TX 77388',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'seller-essence-autos',
    'dealer',
    'Essence Autos',
    NULL,
    'https://www.essenceautostx.com',
    30.0596,
    -95.4616,
    '3102 Louetta Rd, Spring, TX 77388',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'seller-bay-motors',
    'dealer',
    'Bay Motors',
    '936-447-1110',
    'https://www.baymotorstx.com',
    30.1079,
    -95.6374,
    '30210 TX-249, Tomball, TX 77375',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  )
ON CONFLICT(id) DO UPDATE SET
  type = excluded.type,
  name = excluded.name,
  phone = excluded.phone,
  website_url = excluded.website_url,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  location_label = excluded.location_label,
  updated_at = excluded.updated_at;

INSERT INTO model_year_risks (
  id,
  make,
  model,
  year_start,
  year_end,
  rating,
  trim_json,
  engine_json,
  transmission_json,
  issue,
  category,
  severity,
  inspect_for_json,
  remediation_json,
  evidence_ids_json
)
VALUES
  (
    'risk-honda-odyssey-2011-2013-vcm',
    'Honda',
    'Odyssey',
    2011,
    2013,
    'caution',
    NULL,
    NULL,
    NULL,
    'VCM, misfire, piston-ring, sliding-door, and timing-belt history should be verified.',
    'engine',
    7,
    '["Ask for timing-belt service records","Verify misfire or oil-consumption history","Test power sliding doors"]',
    NULL,
    '[]'
  ),
  (
    'risk-honda-pilot-2012-2013-vcm',
    'Honda',
    'Pilot',
    2012,
    2013,
    'caution',
    NULL,
    NULL,
    NULL,
    'Piston-ring, misfire, oil-consumption, and torque-converter behavior should be verified.',
    'engine',
    7,
    '["Ask for oil-consumption or misfire repair history","Check transmission behavior on test drive","Verify timing-belt service"]',
    NULL,
    '[]'
  ),
  (
    'risk-toyota-sienna-2015-2016-sliding-doors',
    'Toyota',
    'Sienna',
    2015,
    2016,
    'preferred',
    NULL,
    NULL,
    NULL,
    'Generally preferred years, with power sliding-door operation still worth checking.',
    'body',
    3,
    '["Test both power sliding doors","Check door cable and latch operation","Verify maintenance records"]',
    NULL,
    '[]'
  ),
  (
    'risk-toyota-highlander-2008-2011-v6-oil-cooler-pipe',
    'Toyota',
    'Highlander',
    2008,
    2011,
    'caution',
    NULL,
    '["2GR-FE V6"]',
    NULL,
    '2GR-FE V6 oil cooler pipe and VVT-i oil hose leak/seep repairs should be verified.',
    'engine',
    6,
    '["Inspect for active oil seepage near oil cooler pipes and VVT-i oil hose","Ask for oil cooler pipe or VVT-i oil hose repair records","Confirm oil level and any recent low-oil-pressure warning history"]',
    '{"description":"Documented replacement of affected oil cooler pipe or VVT-i oil hose reduces concern; active seepage should be repaired before purchase.","resolvesRisk":true}',
    '["https://www.tsbsearch.com/Toyota/T-SB-0201-11","https://www.carcomplaints.com/Toyota/Highlander/2008/tsbs/"]'
  ),
  (
    'risk-toyota-highlander-2014-2015-power-back-door',
    'Toyota',
    'Highlander',
    2014,
    2015,
    'neutral',
    NULL,
    NULL,
    NULL,
    'Power back door may stop during operation or become inoperative; verify operation before purchase.',
    'body',
    3,
    '["Test power back door open and close several times","Check for beeps, stoppage, or stored power-back-door codes","Ask whether T-SB-0023-16 or related repairs were completed"]',
    '{"description":"Documented power back door repair and normal repeated operation reduce concern.","resolvesRisk":true}',
    '["https://www.aboutautomobile.com/Technical-Service-Bulletin/2014/Toyota/Highlander/Hatchback-and-Liftgate","https://www.cars.com/articles/2014-2015-toyota-highlander-power-back-door-issue-1420684625133/"]'
  ),
  (
    'risk-toyota-highlander-2015-eps-recall-check',
    'Toyota',
    'Highlander',
    2015,
    2015,
    'caution',
    NULL,
    NULL,
    NULL,
    'Certain 2015 Highlander vehicles require VIN-specific electric power steering recall verification.',
    'safety',
    8,
    '["Run an NHTSA VIN recall check","Verify electric power steering warning lights are absent","Confirm steering assist is consistent on test drive"]',
    '{"description":"Closed VIN-specific EPS recall or VIN not included resolves this specific recall concern.","resolvesRisk":true}',
    '["https://www.nhtsa.gov/recalls","https://www.arfc.org/autos/toyota/highlander/recalls/000057459001980672000001003/recall.aspx"]'
  ),
  (
    'risk-ford-edge-2015-2018-2-0-ecoboost-coolant-intrusion',
    'Ford',
    'Edge',
    2015,
    2018,
    'caution',
    NULL,
    '["2.0L EcoBoost"]',
    NULL,
    '2.0L EcoBoost coolant intrusion can cause low coolant, white exhaust smoke, rough running, misfire/overheat DTCs, and possible long-block replacement.',
    'engine',
    9,
    '["Check coolant level and coolant-loss history","Look for white exhaust smoke on cold start","Scan for P0300-P0304, P0316, P0217, P1285, or P1299","Ask for engine long-block replacement documentation if repaired"]',
    '{"description":"Documented long-block replacement or a clean pressure-test/inspection reduces concern; unresolved symptoms should be treated as a walk-away risk.","resolvesRisk":true}',
    '["https://dot.report/manufacturer-communications/10214126","https://www.carcomplaints.com/Ford/Edge/2015/tsbs/tsb-tsb-19-2208.shtml"]'
  ),
  (
    'risk-ford-edge-2015-2018-brake-hose-recall',
    'Ford',
    'Edge',
    2015,
    2018,
    'caution',
    NULL,
    NULL,
    NULL,
    'Brake hose recall/investigation history means recall completion and current brake-hose condition should be verified.',
    'safety',
    8,
    '["Run an NHTSA VIN recall check for brake hose campaigns","Inspect front and rear brake hoses for leaks, cracks, and wetness","Confirm firm brake pedal and no brake warning light"]',
    '{"description":"Closed VIN-specific brake hose recalls and clean brake inspection reduce concern.","resolvesRisk":true}',
    '["https://www.nhtsa.gov/recalls","https://oemdtc.com/investigation/PE24027/"]'
  ),
  (
    'risk-ford-explorer-2011-2017-exhaust-co-concern',
    'Ford',
    'Explorer',
    2011,
    2017,
    'caution',
    NULL,
    NULL,
    NULL,
    'Exhaust odor and carbon monoxide concern should be checked, especially after collision repairs or police/upfit history.',
    'safety',
    7,
    '["Ask whether Ford 17N03 or 19N05 program work was completed","Check for exhaust odor during acceleration with rear HVAC running","Inspect liftgate/body sealing and collision repair history","Avoid former police/upfit vehicles unless repairs are well documented"]',
    '{"description":"Documented program completion, clean body sealing, and no odor on test drive reduce concern.","resolvesRisk":true}',
    '["https://dot.report/manufacturer-communications/10162412","https://ford.oemdtc.com/3239/customer-satisfaction-program-17n03-carbon-monoxide-concerns-2011-2017-ford-explorer/"]'
  ),
  (
    'risk-ford-explorer-2013-2017-rear-toe-link',
    'Ford',
    'Explorer',
    2013,
    2017,
    'caution',
    NULL,
    NULL,
    NULL,
    'Rear suspension toe-link recall/program applicability and repair quality should be verified.',
    'safety',
    8,
    '["Run an NHTSA VIN recall check for rear toe-link campaigns","Inspect rear suspension links, bushings, and alignment","Ask whether recall or program repairs used OEM assemblies","Listen for rear suspension noise or wandering during test drive"]',
    '{"description":"Closed VIN-specific toe-link recall/program repairs and clean rear-suspension inspection reduce concern.","resolvesRisk":true}',
    '["https://www.carcomplaints.com/Ford/Explorer/2016/recalls/rear-suspension-toe-link-fracture-20v675000.shtml","https://ford.oemdtc.com/7425/customer-satisfaction-program-21b14-rear-toe-link-ball-joint-inspection-2013-2017-ford-explorer-police-interceptor-utility/"]'
  )
ON CONFLICT(id) DO UPDATE SET
  make = excluded.make,
  model = excluded.model,
  year_start = excluded.year_start,
  year_end = excluded.year_end,
  rating = excluded.rating,
  trim_json = excluded.trim_json,
  engine_json = excluded.engine_json,
  transmission_json = excluded.transmission_json,
  issue = excluded.issue,
  category = excluded.category,
  severity = excluded.severity,
  inspect_for_json = excluded.inspect_for_json,
  remediation_json = excluded.remediation_json,
  evidence_ids_json = excluded.evidence_ids_json;

INSERT INTO source_feeds (
  id,
  seller_id,
  name,
  adapter_key,
  access,
  status,
  inventory_url,
  website_url,
  collection_priority,
  notes,
  created_at,
  updated_at
)
VALUES
  (
    'feed-dealer-car-search-trade-lane-motors',
    'seller-trade-lane-motors',
    'Trade Lane Motors',
    'dealer-car-search',
    'structured-web',
    'active',
    'https://www.tradelanemotors.com/newandusedcars?clearall=1',
    'https://www.tradelanemotors.com',
    10,
    'Healthy plain-fetch Dealer Car Search seed near the family search area.',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'feed-dealer-car-search-king-queen-auto',
    'seller-king-queen-auto',
    'Mr. King and Mrs. Queens Auto Finance LLC',
    'dealer-car-search',
    'structured-web',
    'active',
    'https://www.kingqueenauto.com/newandusedcars?clearall=1',
    'https://www.kingqueenauto.com',
    20,
    'Healthy plain-fetch Dealer Car Search seed; contributes detail URLs and prices.',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'feed-cargurus-toyo-financial-group',
    'seller-toyo-financial-group',
    'Toyo Financial Group on CarGurus',
    'cargurus',
    'structured-web',
    'paused',
    'https://www.cargurus.com/Cars/m-Toyo-Financial-Group-sp357911',
    'https://www.toyofg.com',
    100,
    'Standalone adapter-development feed; review dedupe and terms before scheduled refresh.',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'feed-dealer-com-autostrade',
    'seller-autostrade',
    'Autostrade Dealer.com',
    'dealer-com',
    'structured-web',
    'paused',
    'https://www.autostradetx.net/used-inventory/index.htm',
    'https://www.autostradetx.net',
    105,
    'Standalone Dealer.com adapter-development feed; plain fetch exposes DDC WIS inventory JSON.',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'feed-cargurus-vsa-motorcars',
    'seller-vsa-motorcars',
    'VSA Motorcars on CarGurus',
    'cargurus',
    'structured-web',
    'paused',
    'https://www.cargurus.com/Cars/m-VSA-Motorcars-sp354407',
    'https://www.vsamotorcars.com',
    110,
    'Standalone adapter-development feed because dealer-owned VSA pages returned HTTP 403 to plain fetch.',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'feed-iseecars-ride-motors',
    'seller-ride-motors',
    'Ride Motors LLC on iSeeCars',
    'iseecars',
    'structured-web',
    'paused',
    'https://www.iseecars.com/dealer-3450550-ride-motors-llc-in-cypress-tx',
    'https://www.ridemotorsllc.com',
    120,
    'Standalone adapter-development feed using iSeeCars Vehicle JSON-LD; review terms and dedupe before scheduled refresh.',
    '2026-08-28T00:00:00.000Z',
    '2026-08-28T00:00:00.000Z'
  ),
  (
    'feed-mynextride-auto-land-of-texas',
    'seller-auto-land-of-texas',
    'Auto Land of Texas on MyNextRide',
    'mynextride',
    'structured-web',
    'paused',
    'https://www.mynextride.com/dealers/42/auto-land-of-texas-cypress-tx/inventory',
    'https://www.autolandoftexas.com',
    125,
    'Standalone MyNextRide adapter-development feed; preserves detail URLs and bounded page coverage, review field quality and terms before scheduled refresh.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'feed-dealer-sitemap-i90-motors',
    'seller-i90-motors',
    'I 90 Motors sitemap',
    'dealer-sitemap',
    'structured-web',
    'blocked',
    'https://www.i90motorstx.com/sitemap.xml',
    'https://www.i90motorstx.com',
    155,
    'Sitemap-guided source candidate; sitemap is visible but search-relevant pages returned Datadome HTTP 403 during adapter trial.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'feed-json-ld-ride-motors',
    'seller-ride-motors',
    'Ride Motors LLC generic JSON-LD',
    'json-ld',
    'structured-web',
    'paused',
    'https://www.iseecars.com/dealer-3450550-ride-motors-llc-in-cypress-tx',
    'https://www.ridemotorsllc.com',
    160,
    'Generic JSON-LD adapter-development feed; overlaps iSeeCars-specific feed and should stay paused unless used for parser comparison.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'feed-dealer-car-search-texans-auto-group',
    'seller-texans-auto-group',
    'Texans Auto Group',
    'dealer-car-search',
    'structured-web',
    'paused',
    'https://texansautogroup.com/inventory?clearall=1',
    'https://texansautogroup.com',
    130,
    'Spring Dealer Car Search source candidate; review live parser quality before enabling.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'feed-dealer-car-search-lone-star-auto-center',
    'seller-lone-star-auto-center',
    'Lone Star Auto Center',
    'dealer-car-search',
    'structured-web',
    'paused',
    'https://www.lonestarautocenter.com/inventory?clearall=1',
    'https://www.lonestarautocenter.com',
    135,
    'Spring Dealer Car Search source candidate; review live parser quality before enabling.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'feed-dealer-car-search-spring-motors',
    'seller-spring-motors',
    'Spring Motors',
    'dealer-car-search',
    'structured-web',
    'paused',
    'https://www.spring-motors.com/inventory?clearall=1',
    'https://www.spring-motors.com',
    140,
    'Spring Dealer Car Search source candidate; review live parser quality before enabling.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'feed-carsforsale-essence-autos',
    'seller-essence-autos',
    'Essence Autos on Carsforsale',
    'carsforsale',
    'structured-web',
    'paused',
    'https://www.essenceautostx.com/cars-for-sale',
    'https://www.essenceautostx.com',
    145,
    'Spring Carsforsale-powered source candidate with family-relevant makes/models.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  ),
  (
    'feed-carsforsale-bay-motors',
    'seller-bay-motors',
    'Bay Motors on Carsforsale',
    'carsforsale',
    'structured-web',
    'paused',
    'https://www.baymotorstx.com/cars-for-sale',
    'https://www.baymotorstx.com',
    150,
    'South Tomball Carsforsale-powered source candidate; small inventory useful for adapter validation.',
    '2026-08-29T00:00:00.000Z',
    '2026-08-29T00:00:00.000Z'
  )
ON CONFLICT(id) DO UPDATE SET
  seller_id = excluded.seller_id,
  name = excluded.name,
  adapter_key = excluded.adapter_key,
  access = excluded.access,
  status = excluded.status,
  inventory_url = excluded.inventory_url,
  website_url = excluded.website_url,
  collection_priority = excluded.collection_priority,
  notes = excluded.notes,
  updated_at = excluded.updated_at;
